#dist: trusty

language: cpp
sudo: false
compiler:
    - clang
    - gcc
os:
    - linux

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++" CC="gcc"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++" CC="clang"; fi

script:
  - cmake --build
  - ./bin/foo
